### ISSUE TITLE
SteamCMD-GUI in C#?

### ISSUE THREAD

**Issue by alex1a** [DioJoestar/SteamCMD-GUI#11]
You never thought of developing the software, but in C # ? I made a small replica of the code in C # to be able to test and play other personal features. You think you need any help or there is any to do list in the current version of this software?

Alex

**Comment by DioJoestar** [comment]
This is my first program and how I started learning, I don't have knowledge of C#. [Here is a ToDo list] (https://github.com/DioJoestar/SteamCMD-GUI/labels/ToDo).

I have this project abandoned, so you can improve it as you want always you credit me. One thing I always wanted to do is a usable console, but I don't know how to use sockets, [here you can find some info] (https://developer.valvesoftware.com/wiki/Source_RCON_Protocol).

**Comment by walkerc4** [comment]
I definitely agree this would be more usable if ported to C#, I might work on this in my spare time.

I've done RCON in PHP before and it definitely is not easy. At least there are many C# libraries for things, https://github.com/SteamRE/SteamKit could be used for getting a list of games and appids from the store.

**Comment by Captnwalker1** [comment]
I definitely agree this would be more usable if ported to C#, I might work on this in my spare time.

I've done RCON in PHP before and it definitely is not easy. At least there are many C# libraries for things, https://github.com/SteamRE/SteamKit could be used for getting a list of games and appids from the store.

**Comment by supermorph** [comment]
i know barely little on vb, ive had a dabble here and there, but i did notice something, weather its as simple as it explains,   it is a vb to c# converter  (also does vice versa)

http://converter.telerik.com/

my thoughts was, if this was somehow doable,  i tested one of your files contents, and pasted it in, it did produce something different, so i can attest something is happening, wether its usable is a different matter entirely.

would be wonderful to use this to make a 'starting point' code output, or something that can be used to make a port to linux etc (probably something very difficult id guess)

theres already that microsoft tool on linux, so i reckon it could be made easier,

does this sound viable chaps?  
reason i ask is because im making a dedicated server at home, and wanted a way to utilise what you have done so far, but on ubuntu 16.04,   
(banging my head against the wall with systemd service for garrysmod lol)
